language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.0

script:
  - make fmtcheck errcheck lint
